name: Check Incremental Version

on:
  workflow_dispatch:
    inputs:
      URL:
        description: "ROM 包下载地址"
        required: true

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库文件
        uses: actions/checkout@main

      - name: 提取增量版本号
        run: |
          sudo bash ./make.sh ${{ github.event.inputs.URL }} $GITHUB_ENV

      - name: 发布到 Github Release
        uses: ncipollo/release-action@main
        with:
          name: ${{ env.rom_os_version }}
          tag: ${{ env.rom_os_version }}
          body: |
            机型代号: ${{ env.model }}
            增量版本号: ${{ env.incremental_version }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
